# This is a basic workflow to help you get started with Actions

name: AWS CloudFormation templates deployment

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: "Configure AWS Credentials"
        # You may pin to the exact commit or the version.
        # uses: aws-actions/configure-aws-credentials@cefc5912bc61e2b5a3b049c839fc283c7712d4e0
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          mask-aws-account-id: true 


      - name: AWS CloudFormation "Deploy CloudFormation Stack" Action for GitHub Actions
        # You may pin to the exact commit or the version.
        # uses: aws-actions/aws-cloudformation-github-deploy@dfbee8a4fec90af61b71bafda3890f8c4a2075ef
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          # The name of the CloudFormation stack
          name: VPC-DEV
          # The path or URL to the CloudFormation template
          template: ./Networking.yaml
          # The comma-delimited list of stack template capabilities to acknowledge. Defaults to 'CAPABILITY_IAM'
          capabilities: CAPABILITY_IAM
          # The parameters to override in the stack inputs. The list is comma-delimited, with each entry formatted as <ParameterName>=<ParameterValue>.
          parameter-overrides: >-
            Environment=DEV,
            VpcCidr=172.16.0.0/16
